//
//  MessagesResource.swift
//  CSNetbankingSDK
//
//  Created by Vladimír Nevyhoštěný on 03/09/16.
//  Copyright © 2016 Applifting s.r.o. All rights reserved.
//

import CSCoreSDK

//==============================================================================
public class MessagesResource: NetbankingResource, OptionalPaginatedListEnabled, HasInstanceResource
{
    /**
     * Get messages mandatory resource
     */
    //--------------------------------------------------------------------------
    public var mandatory: MessagesMandatoryResource {
        return MessagesMandatoryResource(path: self.path + "/mandatory", client: self.client);
    }
    
    /**
     * Get messages paginated for current user generated by bank itself. 
     * Message can be read or unread, mandatory and non-mandatory.
     * This call might return different messages based on appId of the caller 
     * (for example, some messages might be specific to an application).
     */
    //--------------------------------------------------------------------------
    public func list(_ parameters: MessagesParameters? = nil, callback: @escaping (_ result: CoreResult<PaginatedListResponse<MessageResponse>>) -> Void)
    {
        ResourceUtils.CallPaginatedList(self, itemJSONKey: "messages", parameters: parameters?.toDictionary(nil), transform: nil, callback: callback)
    }
    
    /**
     * Get the resource of message with a given id
     */
    //--------------------------------------------------------------------------
    public func withId(_ id: Any) -> MessageResource
    {
        return MessageResource(id: id, path: self.path, client: self.client);
    }
}
