//
//  MessageResource.swift
//  CSNetbankingSDK
//
//  Created by Vladimír Nevyhoštěný on 03/09/16.
//  Copyright © 2016 Applifting s.r.o. All rights reserved.
//

import CSCoreSDK

//==============================================================================
public class MessageResource: NetbankingInstanceResource, GetEnabled, UpdateEnabled, DeleteEnabled
{
    /**
     * Get messages attachments resource
     */
    //--------------------------------------------------------------------------
    public var attachments: MessageAttachmentsResource {
        return MessageAttachmentsResource(path: self.path + "/attachments", client: self.client);
    }
    
    /**
     * Get one specific messages for current user generated by bank itself. Message can be read or unread, mandatory and non-mandatory.
     */
    //--------------------------------------------------------------------------
    public func get(_ callback: @escaping (_ result: CoreResult<MessageResponse>) -> () )
    {
        ResourceUtils.CallGet(self, parameters: nil, transform: nil, callback: callback)
    }

    
    /**
     * After message has been read by user it should be marked accordingly by this endpoint.
     */
    //--------------------------------------------------------------------------
    public func update(_ request : UpdateMessageRequest, callback: @escaping (_ result:CoreResult<NetbankingEmptyResponse>)->Void)
    {
        ResourceUtils.CallUpdate(self, payload: request, transform: nil, callback: callback)
    }
    
    /**
     * Resource for deleting message by its identifier. Only read messages can be deleted.
     */
    //--------------------------------------------------------------------------
    public func delete(_ callback: @escaping (_ result:CoreResult<NetbankingEmptyResponse>)->Void)
    {
        ResourceUtils.CallDelete(self, pathSuffix: nil, parameters: nil, transform: nil, callback: callback)
    }
}
